const PRE_OD_CATEGORIES = {
  GENERAL: "General",
  MARKETS: "Markets and customers",
  PLANNING: "Business Planning & Decision Making",
  FINANCIAL: "Financial",
};

const PRE_OD_QUESTIONS = [
  { srNo: 1, category: PRE_OD_CATEGORIES.GENERAL, question: "What, according to you, should be the vision of KNAV?" },
  { srNo: 2, category: PRE_OD_CATEGORIES.GENERAL, question: "What, according to you, should be the mission of KNAV?" },
  { srNo: 3, category: PRE_OD_CATEGORIES.GENERAL, question: "What, according to you should be the core values of KNAV?" },
  { srNo: 4, category: PRE_OD_CATEGORIES.MARKETS, question: "Who according to you should be <<Company's>> Customer?" },
  { srNo: 5, category: PRE_OD_CATEGORIES.MARKETS, question: "What would you want the <<Company's>> customer to visualize us \"about\"?" },
  { srNo: 6, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the value proposition of KNAV?" },
  { srNo: 7, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the opportunity size (in terms of business and potential revenue) for KNAV? Please elaborate on the markets you plan to cater to, the key elements of your competitive differentiation, and what you consider to be the \"moat\"." },
  { srNo: 8, category: PRE_OD_CATEGORIES.MARKETS, question: "List down the various products that will be sold by KNAV. What customer problem(s) does your business solve?" },
  { srNo: 9, category: PRE_OD_CATEGORIES.MARKETS, question: "How would you segment your target customers based on dimensions such as geography, demographics, price sensitivity, product delivery weighting, and customer spending habits (occasional, routine, etc.)?" },
  { srNo: 10, category: PRE_OD_CATEGORIES.MARKETS, question: "Plans to tap the market by creating market awareness of existing offerings?" },
  { srNo: 11, category: PRE_OD_CATEGORIES.MARKETS, question: "Plans to tap the market by creating market awareness of new offerings (if any)?" },
  { srNo: 12, category: PRE_OD_CATEGORIES.MARKETS, question: "Why should customers buy from you?" },
  { srNo: 13, category: PRE_OD_CATEGORIES.MARKETS, question: "What is your portrait gap for the competitors that can be addressed?" },
  { srNo: 14, category: PRE_OD_CATEGORIES.MARKETS, question: "How will the business distinguish itself against competitors in the market (e.g., lower turnaround time, lower costs, better design, etc.)?" },
  { srNo: 15, category: PRE_OD_CATEGORIES.MARKETS, question: "How large is the addressable market for your new offering, in terms of potential revenue?" },
  { srNo: 16, category: PRE_OD_CATEGORIES.MARKETS, question: "What are the challenges faced by the industry? How do you plan to navigate these issues successfully?" },
  { srNo: 17, category: PRE_OD_CATEGORIES.MARKETS, question: "What are the market segments that are planned to be entered in the next 1-3 years?" },
  { srNo: 18, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the \"Revenue Model\"? Customer pays how much money? How is the money collected? What is the cost?" },
  { srNo: 19, category: PRE_OD_CATEGORIES.PLANNING, question: "What is the current and next 1-2 years' organizational chart?" },
  { srNo: 20, category: PRE_OD_CATEGORIES.PLANNING, question: "Do you have a core set of advisors? Have you identified potential additional Board Members?" },
  { srNo: 21, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are the ongoing and additional infrastructure requirements for the pan-india and international operations (e.g., premises, specialized services, etc.)? Please outline the expected investments in each." },
  { srNo: 22, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Please provide detailed break-up of Fixed Cost and Variable Cost (Total Cost / Unit Cost)." },
  { srNo: 23, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Rationale for investment and potential for revenue generation (%)." },
  { srNo: 24, category: PRE_OD_CATEGORIES.PLANNING, question: "Considering the significance of R&D in the industry, innovation will play a crucial role in terms of market positioning and billing. What are the direction and investment towards R&D and product portfolio?" },
  { srNo: 25, category: PRE_OD_CATEGORIES.PLANNING, question: "How is innovation being used as a weapon for business expansion?" },
  { srNo: 26, category: PRE_OD_CATEGORIES.PLANNING, question: "How is innovation being used in internal business operations?" },
  { srNo: 27, category: PRE_OD_CATEGORIES.PLANNING, question: "How is innovation being used in driving operational excellence & reduction of costs?" },
  { srNo: 28, category: PRE_OD_CATEGORIES.PLANNING, question: "How do various teams within the organization - such as Sales, Marketing, Operations, and Management - contribute to driving innovation in the business?" },
  { srNo: 29, category: PRE_OD_CATEGORIES.PLANNING, question: "What is the focus of innovative techniques employed by your organization? How do they help for improvement, cost reduction, etc.?" },
  { srNo: 30, category: PRE_OD_CATEGORIES.PLANNING, question: "Create a detailed Roadmap: Business milestones and a roadmap document that silhouettes the steps taken towards the milestones." },
  { srNo: 31, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Please provide an overview of the business's financial controls and past audit results, highlighting expected revenue break-up over the next 5 years, expected gross margin break-up over the next 5 years, major expense categories and their drivers, financial lever adjustments, and financial investment in human capital." },
  { srNo: 32, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Please highlight the current capital/debt structure of KNAV. Please provide a breakdown of planned fund utilization over the next 3-5 years covering hiring, infrastructure, marketing, and working capital." },
  { srNo: 33, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Please outline your funding and deployment plans over the next 3-5 years, including sources of funds, capital expenditure, promotional activities, and working capital requirements." },
  { srNo: 34, category: PRE_OD_CATEGORIES.MARKETS, question: "Are there any actual services or services offered to consumers?" },
  { srNo: 35, category: PRE_OD_CATEGORIES.MARKETS, question: "How is customer feedback/improvement product drawing seen?" },
  { srNo: 36, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the current customer acquisition cost?" },
  { srNo: 37, category: PRE_OD_CATEGORIES.MARKETS, question: "How many distinct markets does the company currently operate, segmented by geography or market positioning (e.g., premium, mid-range, value)?" },
  { srNo: 38, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the average margin of the current product offerings?" },
  { srNo: 39, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the average discount given to customers?" },
  { srNo: 40, category: PRE_OD_CATEGORIES.MARKETS, question: "How does your pricing differ between your D2C platform and marketplace (Amazon, Flipkart, Nykaa, etc.)?" },
  { srNo: 41, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the current and projected growth for various distribution channels?" },
  { srNo: 42, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Current Return on Ads Spend (ROAS)?" },
  { srNo: 43, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Current Customer Retention/Repeat Rate?" },
  { srNo: 44, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the current and projected revenue and EBITDA for key markets?" },
  { srNo: 45, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is your monthly marketing budget?" },
  { srNo: 46, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How much of revenue is being spent on marketing?" },
  { srNo: 47, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How many influencer/social media personas are marketing?" },
  { srNo: 48, category: PRE_OD_CATEGORIES.MARKETS, question: "Is community building an integral part of the company's positioning? Are free samples included with premium paid version?" },
  { srNo: 49, category: PRE_OD_CATEGORIES.MARKETS, question: "Does the company focus on brand ambassadors?" },
  { srNo: 50, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What marketing technology (MarTech) stack is being used?" },
  { srNo: 51, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are the top performance marketing channels (e.g., Meta, Google, Pinterest)?" },
  { srNo: 52, category: PRE_OD_CATEGORIES.MARKETS, question: "Is the company present across all social media platforms?" },
  { srNo: 53, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the Monthly Active Users (MAU)?" },
  { srNo: 54, category: PRE_OD_CATEGORIES.FINANCIAL, question: "On average, how long do customers keep items in their cart before completing the purchase?" },
  { srNo: 55, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average size of the physical store?" },
  { srNo: 56, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average rent paid per physical store?" },
  { srNo: 57, category: PRE_OD_CATEGORIES.MARKETS, question: "How many years does the brand currently operate?" },
  { srNo: 58, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What types of formats do you use (e.g., Flagship, Kiosks, pop-up, etc.)?" },
  { srNo: 59, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are the key elements of store interiors/ambience?" },
  { srNo: 60, category: PRE_OD_CATEGORIES.FINANCIAL, question: "For existing stores, what is the average capital expenditure per store?" },
  { srNo: 61, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average revenue per store?" },
  { srNo: 62, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are the margin structures for distributors, retailers and wholesalers?" },
  { srNo: 63, category: PRE_OD_CATEGORIES.MARKETS, question: "What is the timeline for planned store openings?" },
  { srNo: 64, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average investment required per store for a franchise model?" },
  { srNo: 65, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the typical gestation period for a business cycle?" },
  { srNo: 66, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How many stores are currently loss-making, at break-even or profitable?" },
  { srNo: 67, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the expected inventory?" },
  { srNo: 68, category: PRE_OD_CATEGORIES.MARKETS, question: "Are sales staff incentive-based? Are sales on products or overall?" },
  { srNo: 69, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average monthly footfall per store/location?" },
  { srNo: 70, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average monthly sales per store?" },
  { srNo: 71, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How many staff members work at each store?" },
  { srNo: 72, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are your current sales per square foot?" },
  { srNo: 73, category: PRE_OD_CATEGORIES.MARKETS, question: "Is the company involved in manufacturing its products?" },
  { srNo: 74, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are your average Customer Acquisition Cost?" },
  { srNo: 75, category: PRE_OD_CATEGORIES.MARKETS, question: "Where are the manufacturing units or partner facilities located?" },
  { srNo: 76, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What are your monthly manufacturing production capacity (units)?" },
  { srNo: 77, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What % of capacity is currently utilized?" },
  { srNo: 78, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the internal loss percentage?" },
  { srNo: 79, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is wastage percentage?" },
  { srNo: 80, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Have you seen any major supply chain/raw material cost fluctuations?" },
  { srNo: 81, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Do raw material fluctuations affect Gross Profit Margin frequently?" },
  { srNo: 82, category: PRE_OD_CATEGORIES.MARKETS, question: "Are you sourcing products from same or multiple/many manufacturers?" },
  { srNo: 83, category: PRE_OD_CATEGORIES.PLANNING, question: "Who is the organizational head for current operations?" },
  { srNo: 84, category: PRE_OD_CATEGORIES.PLANNING, question: "What does the overall organizational structure look like?" },
  { srNo: 85, category: PRE_OD_CATEGORIES.PLANNING, question: "Do the business has full-time/part-time employees?" },
  { srNo: 86, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Who handles the distribution channels?" },
  { srNo: 87, category: PRE_OD_CATEGORIES.PLANNING, question: "What are the key performance metrics (KPIs) of the organization?" },
  { srNo: 88, category: PRE_OD_CATEGORIES.PLANNING, question: "What is the current employee strength?" },
  { srNo: 89, category: PRE_OD_CATEGORIES.PLANNING, question: "How is employee performance measured and rewarded?" },
  { srNo: 90, category: PRE_OD_CATEGORIES.PLANNING, question: "What are your data privacy and customer protection practices?" },
  { srNo: 91, category: PRE_OD_CATEGORIES.FINANCIAL, question: "For how long does an average user keep the app installed for?" },
  { srNo: 92, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How many active sellers are present on the app?" },
  { srNo: 93, category: PRE_OD_CATEGORIES.FINANCIAL, question: "How many past users are there on the app?" },
  { srNo: 94, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the current burn rate?" },
  { srNo: 95, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the expected timeline for achieving contribution margin (CM) positivity across CM1, CM2, and CM3?" },
  { srNo: 96, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the dependability of the business?" },
  { srNo: 97, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average contribution rate?" },
  { srNo: 98, category: PRE_OD_CATEGORIES.FINANCIAL, question: "What is the average order value?" },
  { srNo: 99, category: PRE_OD_CATEGORIES.FINANCIAL, question: "Is the company looking to acquire/be acquired/take over?" },
];

function getPreOdQuestions() {
  return PRE_OD_QUESTIONS.map((item) => ({
    ...item,
    section: item.srNo <= 33 ? "A" : "B",
  }));
}

module.exports = {
  PRE_OD_CATEGORIES,
  PRE_OD_QUESTIONS,
  getPreOdQuestions,
};
