const PRE_OD_CATEGORIES = {
  GENERAL: "General",
  MARKETS: "Markets and customers",
  PLANNING: "Business Planning & Decision Making",
  FINANCIAL: "Financials",
};

const PRE_OD_QUESTIONS = [
  { srNo: 1, category: PRE_OD_CATEGORIES.GENERAL, question: 'What, according to you, should be the vision of KNAV?' },
  { srNo: 2, category: PRE_OD_CATEGORIES.GENERAL, question: 'What, according to you, should be the mission of KNAV?' },
  { srNo: 3, category: PRE_OD_CATEGORIES.GENERAL, question: 'What, according to you, should be the core values of KNAV?' },
  { srNo: 4, category: PRE_OD_CATEGORIES.MARKETS, question: 'Who according to you should be KNAV\'s Customer/s?' },
  { srNo: 5, category: PRE_OD_CATEGORIES.MARKETS, question: 'What would customers of KNAV consider as “value”?' },
  { srNo: 6, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the theory of business of KNAV?' },
  { srNo: 7, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the overarching theory of business and growth strategy for KNAV? Please elaborate on the markets you plan to cater to, the key elements of your competitive differentiation, and what you envision as the firm’s USP.' },
  { srNo: 8, category: PRE_OD_CATEGORIES.MARKETS, question: 'List down the various products that are offered by KNAV. What customer problem/s does your business solve?' },
  { srNo: 9, category: PRE_OD_CATEGORIES.MARKETS, question: 'How would you segment your typical customer across key dimensions such as geography, demographics, price sensitivity, product delivery complexity, and customer type (e.g., end consumers, retailers, etc.)' },
  { srNo: 10, category: PRE_OD_CATEGORIES.MARKETS, question: 'Plan to tap the market by creating market awareness of existing offerings' },
  { srNo: 11, category: PRE_OD_CATEGORIES.MARKETS, question: 'Plan to tap the market by creating market awareness of new offerings (if any)' },
  { srNo: 12, category: PRE_OD_CATEGORIES.MARKETS, question: 'Who are your main competitors?' },
  { srNo: 13, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is your portfolio gap for the competitors that can be addressed?' },
  { srNo: 14, category: PRE_OD_CATEGORIES.MARKETS, question: 'How will the business strategy be to compete and grow in the market (e.g. faster turnaround time, lower costs, better designs etc.)?' },
  { srNo: 15, category: PRE_OD_CATEGORIES.MARKETS, question: 'How large is the addressable market for your core offering, in terms of potential sales?' },
  { srNo: 16, category: PRE_OD_CATEGORIES.MARKETS, question: 'What are the challenges faced by the industry? How do you plan to mitigate their impact on the firm?' },
  { srNo: 17, category: PRE_OD_CATEGORIES.MARKETS, question: 'What are the market segments that are planned to be catered in the next 2-3 years?' },
  { srNo: 18, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the “Go to Market”/ Customer reach-out strategy? What is the execution plan for the same?' },
  { srNo: 19, category: PRE_OD_CATEGORIES.PLANNING, question: 'What is the current and next 1-3 years’ organization chart?' },
  { srNo: 20, category: PRE_OD_CATEGORIES.PLANNING, question: 'Do you have a current set of Advisors? Have you identified potential external Board Members?' },
  { srNo: 21, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What are the ongoing and anticipated infrastructure requirements for Pan-India and international operations (e.g., premises, outsourced services, etc.)? Please outline the expected investments towards these, including near-term CAPEX (within 1 year) and long-term CAPEX (over the next 2–3 years).' },
  { srNo: 22, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Rationale for investment and potential for success (expected ROI)' },
  { srNo: 23, category: PRE_OD_CATEGORIES.PLANNING, question: 'Considering the significance of R&D in this industry, innovation will play a significant role towards core competency building. What are the other ways in which innovation will play a crucial role?' },
  { srNo: 24, category: PRE_OD_CATEGORIES.PLANNING, question: 'How is innovation encouraged in development of business operations?' },
  { srNo: 25, category: PRE_OD_CATEGORIES.MARKETS, question: 'How is innovation encouraged in selling?' },
  { srNo: 26, category: PRE_OD_CATEGORIES.PLANNING, question: 'How is innovation encouraged in achieving operational excellence & economies of scale?' },
  { srNo: 27, category: PRE_OD_CATEGORIES.PLANNING, question: 'How do various teams within the organization - such as Sales, Operations/Technical, and Management - contribute to driving innovation in the business?' },
  { srNo: 28, category: PRE_OD_CATEGORIES.PLANNING, question: 'What is the focus of innovation techniques employed in your organization (towards productivity/process improvement, cost reduction, etc.)?' },
  { srNo: 29, category: PRE_OD_CATEGORIES.PLANNING, question: 'Create a timeline to achieve innovation milestones and a roadmap document that will assess the steps taken towards the milestones.' },
  { srNo: 30, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Please provide an overview of the business\'s financial outlook and past investments, covering the following aspects:" 1. Expected revenue break-up over the next 3 years 2. Expected cost structure break-up over the next 3 years 3. Estimated working capital requirements over the next 3 years 4. Financial investments made to date in capital expenditure (e.g., platform/product development) 5. Financial investments made to date in building human capital' },
  { srNo: 31, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Please highlight the current capitalization table of KNAV' },
  { srNo: 32, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Please provide a breakdown of planned fund utilization over the next 2–3 years, specifically across the following areas:" 1. Hiring and onboarding of new employees 2. New product/platform development 3. Marketing and promotional efforts 4. Working capital requirements' },
  { srNo: 33, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Please outline your funding and deployment plans over the next 1–3 years, including the following details:" 1. Potential sources of funding (e.g., banks, private equity funds, promoter funds, etc.) 2. Planned fund deployment towards capital expenditure 3. Planned fund deployment towards promotional and marketing expenditure 4. Planned fund deployment towards working capital requirements' },
  { srNo: 34, category: PRE_OD_CATEGORIES.MARKETS, question: 'Are there any product bundles or combos offered to customers?' },
  { srNo: 35, category: PRE_OD_CATEGORIES.MARKETS, question: 'How is customer feedback incorporated into product development?' },
  { srNo: 36, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the current inventory turnover ratio?' },
  { srNo: 37, category: PRE_OD_CATEGORIES.MARKETS, question: 'How many distinct brands does the company currently operate, segmented by price point or market positioning (e.g., premium, mid-range, value)?' },
  { srNo: 38, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the price range of the current product offerings?' },
  { srNo: 39, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the average discount provided to customers ?' },
  { srNo: 40, category: PRE_OD_CATEGORIES.MARKETS, question: 'How does your pricing differ between your D2C platform and marketplaces (Amazon, Flipkart, Nykaa, etc.)?' },
  { srNo: 41, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the current and projected split across various distribution channels?' },
  { srNo: 42, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Current Return on Ads Spend (ROAS)' },
  { srNo: 43, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Current Customer retention - MoM & YoY' },
  { srNo: 44, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the current split between online and offline marketing spends?' },
  { srNo: 45, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is your monthly marketing budget?' },
  { srNo: 46, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What % of revenue do you spend on marketing?' },
  { srNo: 47, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'How actively does the brand do performance marketing?' },
  { srNo: 48, category: PRE_OD_CATEGORIES.MARKETS, question: 'Is community building an integral part of the company\'s positioning?' },
  { srNo: 49, category: PRE_OD_CATEGORIES.MARKETS, question: 'Are free samples included with product deliveries?' },
  { srNo: 50, category: PRE_OD_CATEGORIES.MARKETS, question: 'Does the company have any brand ambassador?' },
  { srNo: 51, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What products have the highest LTV-linked retention rates?' },
  { srNo: 52, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What are your top-performing acquisition channels (e.g., Meta, Google, influencers)?' },
  { srNo: 53, category: PRE_OD_CATEGORIES.MARKETS, question: 'Is the company present on any social media platforms ?' },
  { srNo: 54, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is your LTV?' },
  { srNo: 55, category: PRE_OD_CATEGORIES.MARKETS, question: 'On average, how long do customers keep items in their cart before completing the purchase?' },
  { srNo: 56, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average size of the physical stores?' },
  { srNo: 57, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average payback period for a store?' },
  { srNo: 58, category: PRE_OD_CATEGORIES.MARKETS, question: 'How many stores does the brand currently operate?' },
  { srNo: 59, category: PRE_OD_CATEGORIES.MARKETS, question: 'What types of formats do you operate (e.g., flagship, kiosk, pop-up, outlet)?' },
  { srNo: 60, category: PRE_OD_CATEGORIES.MARKETS, question: 'What store formats are in use: EBOs, MBOs, GT, MT?' },
  { srNo: 61, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'If operating EBOs, what is the average capital expenditure per store?' },
  { srNo: 62, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average revenue per sqft?' },
  { srNo: 63, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What are the margin structures for distributors, stockists and retailers?' },
  { srNo: 64, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the timeline of planned store openings?' },
  { srNo: 65, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average investment required per store by a franchise owner?' },
  { srNo: 66, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the typical payback period for a franchise store?' },
  { srNo: 67, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'How many stores are currently loss-making, at breakeven or profitable?' },
  { srNo: 68, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the store churn rate?' },
  { srNo: 69, category: PRE_OD_CATEGORIES.MARKETS, question: 'Are sales staff incentivized to push certain products or upsell?' },
  { srNo: 70, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average footfall per store per day/week?' },
  { srNo: 71, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average monthly sales per store?' },
  { srNo: 72, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'How many staff members work in each store?' },
  { srNo: 73, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What are average monthly cost per store?' },
  { srNo: 74, category: PRE_OD_CATEGORIES.MARKETS, question: 'Is the company involved in manufacturing its products?' },
  { srNo: 75, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What are your average Customer Acquisition Cost?' },
  { srNo: 76, category: PRE_OD_CATEGORIES.MARKETS, question: 'Where are the manufacturing units or partner facilities located?' },
  { srNo: 77, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is your current monthly production capacity (units)?' },
  { srNo: 78, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What % of capacity is currently utilized?' },
  { srNo: 79, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the normal loss percentage?' },
  { srNo: 80, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is wastage percentage?' },
  { srNo: 81, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Have you seen any major cost escalations recently in raw materials?' },
  { srNo: 82, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Do raw material fluctuations affect Gross Profit margins frequently?' },
  { srNo: 83, category: PRE_OD_CATEGORIES.MARKETS, question: 'Are you managing production in-house or via third-party manufacturers?' },
  { srNo: 84, category: PRE_OD_CATEGORIES.MARKETS, question: 'What is the organizational structure for offline operations?' },
  { srNo: 85, category: PRE_OD_CATEGORIES.PLANNING, question: 'What does the overall organizational structure look like?' },
  { srNo: 86, category: PRE_OD_CATEGORIES.PLANNING, question: 'Are the founders involved full-time in the business?' },
  { srNo: 87, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What has been the staff churn rate?' },
  { srNo: 88, category: PRE_OD_CATEGORIES.PLANNING, question: 'Who are the key managerial personnel (KMP) in the organization?' },
  { srNo: 89, category: PRE_OD_CATEGORIES.PLANNING, question: 'What is the current employee strength?' },
  { srNo: 90, category: PRE_OD_CATEGORIES.PLANNING, question: 'How do you monitor compliance across geographies?' },
  { srNo: 91, category: PRE_OD_CATEGORIES.PLANNING, question: 'What are your data privacy and customer protection practices?' },
  { srNo: 92, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'For how long does an average customer keep the app installed ?' },
  { srNo: 93, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'How many active users are present on the app ?' },
  { srNo: 94, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'How many paid users are there on the app ?' },
  { srNo: 95, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the monthly burn?' },
  { srNo: 96, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the expected timeline for achieving contribution margin (CM) positivity across different levels?" 1. CM1 positivity 2. CM2 positivity 3. CM3 positivity' },
  { srNo: 97, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'When is EBITDA positivity on the horizon?' },
  { srNo: 98, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the average sales return rate?' },
  { srNo: 99, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'What is the cash runway available?' },
  { srNo: 100, category: PRE_OD_CATEGORIES.FINANCIAL, question: 'Is the company looking to raise debt/ equity in the next round?' },
];

function getPreOdQuestions() {
  return PRE_OD_QUESTIONS.map((item) => ({
    ...item,
    section: item.srNo <= 33 ? "A" : "B",
  }));
}

module.exports = {
  PRE_OD_CATEGORIES,
  PRE_OD_QUESTIONS,
  getPreOdQuestions,
};
